### ISSUE TITLE
Web UI hangs after loading a resource

### ISSUE THREAD

**Issue by arnikz** [dsd-sztaki-hu/LODmilla-frontend#1]
Hi,

While fiddling with this promising tool I ran into the following problem. Sometimes when selecting a new linked resource from the right panel (Links in/out), the interface hangs and shows never- ending 'Working...' in the lower-left corner. In particular, once you've got a couple of related nodes on the canvas, the only thing that helps is to reload the page, resulting in a complete loss of the exploratory work. It seems that the issue is with incorrectly deployed RDF resources (or non-RDF resources such as http://www.example.com). Could you please have a look at it? Thanks.

**Comment by arnikz** [comment]
Hi @micsik, please let me know if you (or someone else) could look at it.

**Comment by micsik** [comment]
Hi @arnikz, this is fixed now.
András

**Comment by arnikz** [comment]
Hi Andras @micsik, I've tried your updated version on DBpedia with the search term _Plant breeding_, followed by [Q788558](http://wikidata.dbpedia.org/resource/Q788558) in the _Links out/Same as_ field. The issue with the frozen interface showing 'Working...' seems to be fixed now but I encountered the following:  for example, the above URI keeps on 'Loading...' for a while and then ends with a '?' despite it does resolve (e.g. using a web browser). Could you please check? Thanks.

**Comment by micsik** [comment]
Hi Arnold i @arnikz, the ? mark means the RDF could not be fetched, because neither SPARQL endpoint nor URI dereferencing succeeded. I added the wikidata SPARQL endpoint, so it works now.

**Comment by arnikz** [comment]
That's great, thanks!
