### ISSUE TITLE
Proxy implementation to render data behind a firewall

### ISSUE THREAD

**Issue by agcunha** [dsd-sztaki-hu/LODmilla-frontend#5]
My data is behind a firewall available on apache fuseki for developing purposes. 

Query lookup is already working but data cannot be rendered in nodes.

Error: failed to download a resource: http://URL/<entity>

I commented this line with no sucess:

this.serverProxyUrl = '';  //'http://munkapad.sztaki.hu/lodback/';

Ps: data can be read by Pubby or lodview

**Comment by agcunha** [comment]
Sorry, i thought that LODmilla-frontend works without a proxy as Relfinder does.

I just found the backend project.

**Comment by micsik** [comment]
Yes, we wrote our own backend for
- special graph queries
- saving and sharing graph views
- accessing linked data without a SPARQL endpoint and without JSONP

**Comment by agcunha** [comment]
How can i make a jar file for hu.mta.sztaki.lod?
lod_resource_proxy.jsp depends of hu.mta.sztaki.lod.GraphUtils and it's under src folder but not built.

I tried using ant but it complains of a dependecy of IntelliJ IDE modules.

Can you provide jar file in backend project?

**Comment by micsik** [comment]
I uploaded a war file, but it contains the default SQL user name and password. I also changed build.xml a bit, I hope now ant can build it without Idea.
